#pragma once
const int HEIGHT = 20;
const int WIDTH = 20;
const char BACTERIUM_SKIN = 'B';
const char FOOD_SKIN = '|';
const char POISON_SKIN = '-';
const int ALL_BACTERIUMS_START = 10;
const int HOW_MANY_COMMAND = 64;
const int HOW_MANY_BACTERS_NEED_TO_DIED_A_NEW_GENERATION = 8;
const int HOW_MANY_FOODS = 10;
const int HOW_MANY_FOOD_GET_LIVE_POINTERS = 10;
const int HOW_MANU_LIVE_POINTERS_HAVE_BACTERIUM = 20;
const int HOW_MANY_LIVE_POINTERS_GIVE_PHOTOSYNTHESIS = 2;
const int HOW_MANY_COMMAND_EXIST = 4;
const int HOW_MANY_POISON = 4;
const int HOW_MUCH_POISON_DANAGE = 5;
const int NUMBER_COMMAND_MOVE = 0;
const int NUMBER_COMMAND_GRAB = 1;
const int NUMBER_COMMAND_GO_TO = 2;
const int NUMBER_COMMAND_PHOTOSYNTHESIS = 3;

